name: Build UI

on:
  pull_request:
  push:
    branches:
      - master
      - releases/*

jobs:
  install_and_build:
    runs-on: ubuntu-latest

    permissions:
      contents: read

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup node 20
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Get yarn cache
        id: yarn-cache
        run: echo "::set-output name=dir::$(yarn cache dir)"

      - name: Cache Node.js modules
        uses: actions/cache@v3
        with:
          path: ${{ steps.yarn-cache.outputs.dir }}
          key: ${{ runner.OS }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.OS }}-yarn-

      - name: Install dependencies and test build
        run: yarn

      - name: Run build
        run: yarn build

      - name: Push to Stellate
        if: github.ref == 'refs/heads/master'
        run: npx stellate push
        env:
          STELLATE_TOKEN: ${{ secrets.STELLATE_TOKEN }}
